largecommits : 
  enabled: false

approvals: 
  includeAuthor: true
  minimum: 2
  enabled: true

specification:
  enabled: false

license :
  enabled: false

X-Zalando-Type: tools
X-Zalando-Team: opensource
